description: "3狼 + 机械狼 + 魔镜少女 + 女巫 + 猎人 + 守墓人 + 4村民"

roster:
  - 机械狼
  - 黑狼王
  - 石像鬼
  - 吸血鬼
  - 魔镜少女
  - 预言家
  - 女巫
  - 猎人
  - 守卫
  - 守墓人
  - 骑士
  - 白痴

game_stages:
  - name: 夜晚
    actions:
      - 守卫
      - 预言家
      - 魔镜少女
      - 机械狼
      - 石像鬼
      - 狼人
      - 吸血鬼
      - 女巫

  - name: 白天
    actions:
      - speech
      - vote
