description: "3狼 + 石像鬼 + 预言家 + 女巫 + 猎人 + 守墓人 + 4村民"

roster:
  - 石像鬼
  - 狼人
  - 狼人
  - 狼人
  - 预言家
  - 女巫
  - 猎人
  - 守墓人
  - 村民
  - 村民
  - 村民
  - 村民

game_stages:
  - name: 夜晚
    actions:
      - 预言家
      - 石像鬼
      - 狼人
      - 女巫

  - name: 白天
    actions:
      - speech
      - vote
