description: "3狼 + 机械狼 + 灵镜少女 + 女巫 + 猎人 + 守卫 + 4村民"

roster:
  - 机械狼
  - 狼人
  - 狼人
  - 狼人
  - 灵镜少女
  - 女巫
  - 猎人
  - 守卫
  - 村民
  - 村民
  - 村民
  - 村民

game_stages:
  - name: 夜晚
    actions:
      - 灵镜少女
      - 机械狼
      - 狼人
      - 女巫

  - name: 白天
    actions:
      - speech
      - vote
