description: "2狼 + 预言家 + 女巫 + 猎人 + 3村民"

roster:
  - 狼人
  - 狼人
  - 预言家
  - 女巫
  - 猎人
  - 村民
  - 村民
  - 村民

game_stages:
  - name: 夜晚
    actions:
      - 狼人
      - 女巫
      - 预言家

  - name: 白天
    actions:
      - speech
      - vote
