description: "黑狼王 + 3狼 + 预言家 + 女巫 + 猎人 + 守卫 + 4村民"

roster:
  - 黑狼王
  - 狼人
  - 狼人
  - 狼人
  - 预言家
  - 女巫
  - 猎人
  - 守卫
  - 村民
  - 村民
  - 村民
  - 村民

game_stages:
  - name: 夜晚
    actions:
      - 预言家
      - 守卫
      - 狼人
      - 女巫

  - name: 白天
    actions:
      - speech
      - vote
